global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.12.204:9101']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics'

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8081']
    metrics_path: '/metrics'

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper-exporter:9141']

  - job_name: 'kafka-consumer'
    static_configs:
      - targets: [ 'host.docker.internal:8001' ]
    metrics_path: '/'